import json
import os
from pathlib import Path


class RoadDataAdapter:
    def __init__(self, source_path: str | None = None):
        self.source_path = Path(source_path or os.getenv("ROADWATCH_DATA_FILE", "data/road_samples.json"))

    def load_roads(self):
        if not self.source_path.exists():
            return self._default_roads()

        try:
            return json.loads(self.source_path.read_text(encoding="utf-8"))
        except Exception:
            return self._default_roads()

    def _default_roads(self):
        return [
            {
                "id": 1,
                "road": "NH-44 Krishnagiri Bypass",
                "name": "NH-44 Krishnagiri Bypass",
                "type": "NH",
                "district": "Krishnagiri",
                "state": "Tamil Nadu",
                "status": "Critical",
                "risk": "High",
                "severity": "high",
                "lat": 12.5266,
                "lng": 78.2137,
                "contractor": "L&T Infrastructure Pvt Ltd",
                "budget_sanctioned": "Rs 1.5 crore",
                "budget_spent": "Rs 0.92 crore",
                "budget_allocated": 15000000,
                "budget_spent_amount": 9200000,
                "hazard_type": "Pothole Cluster",
                "complaints": 47,
                "authority": "NHAI",
                "last_repair": "2025-11-18",
                "next_review": "2026-06-20",
                "source_url": "https://morth.nic.in/",
                "issue_summary": "Recurring pothole cluster near a high-traffic bypass segment.",
            },
            {
                "id": 2,
                "road": "SH-9 Chennai-Pondicherry Road",
                "name": "SH-9 Chennai-Pondicherry Road",
                "type": "SH",
                "district": "Villupuram",
                "state": "Tamil Nadu",
                "status": "Under Repair",
                "risk": "Medium",
                "severity": "medium",
                "lat": 11.9401,
                "lng": 79.8083,
                "contractor": "GR Infraprojects",
                "budget_sanctioned": "Rs 0.85 crore",
                "budget_spent": "Rs 0.51 crore",
                "budget_allocated": 8500000,
                "budget_spent_amount": 5100000,
                "hazard_type": "Road Cave-in",
                "complaints": 31,
                "authority": "Tamil Nadu PWD",
                "last_repair": "2026-01-09",
                "next_review": "2026-07-01",
                "source_url": "https://data.gov.in/",
                "issue_summary": "Cave-in risk and surface cracking reported after monsoon traffic.",
            },
            {
                "id": 3,
                "road": "NH-48 Bengaluru Outer Ring Road",
                "name": "NH-48 Bengaluru Outer Ring Road",
                "type": "NH",
                "district": "Bengaluru Urban",
                "state": "Karnataka",
                "status": "Critical",
                "risk": "High",
                "severity": "high",
                "lat": 12.9716,
                "lng": 77.5946,
                "contractor": "HCC Ltd",
                "budget_sanctioned": "Rs 2.2 crore",
                "budget_spent": "Rs 1.8 crore",
                "budget_allocated": 22000000,
                "budget_spent_amount": 18000000,
                "hazard_type": "Waterlogging and Potholes",
                "complaints": 89,
                "authority": "BBMP / NHAI",
                "last_repair": "2025-09-27",
                "next_review": "2026-06-12",
                "source_url": "https://morth.nic.in/",
                "issue_summary": "Waterlogging and potholes are affecting a dense commuter corridor.",
            },
            {
                "id": 4,
                "road": "NH-19 Delhi-Agra Black Spot",
                "name": "NH-19 Delhi-Agra Black Spot",
                "type": "NH",
                "district": "Mathura",
                "state": "Uttar Pradesh",
                "status": "Critical",
                "risk": "High",
                "severity": "high",
                "lat": 27.4924,
                "lng": 77.6737,
                "contractor": "Jaypee Infratech",
                "budget_sanctioned": "Rs 3.5 crore",
                "budget_spent": "Rs 2.9 crore",
                "budget_allocated": 35000000,
                "budget_spent_amount": 29000000,
                "hazard_type": "Accident Black Spot",
                "complaints": 112,
                "authority": "NHAI",
                "last_repair": "2025-10-08",
                "next_review": "2026-06-18",
                "source_url": "https://morth.nic.in/",
                "issue_summary": "Crash-prone segment needs black spot mitigation, signage, and inspection.",
            },
            {
                "id": 5,
                "road": "AP-SH-1 Vijayawada-Guntur",
                "name": "AP-SH-1 Vijayawada-Guntur",
                "type": "SH",
                "district": "Guntur",
                "state": "Andhra Pradesh",
                "status": "Under Repair",
                "risk": "Medium",
                "severity": "medium",
                "lat": 16.3067,
                "lng": 80.4365,
                "contractor": "NCC Limited",
                "budget_sanctioned": "Rs 0.9 crore",
                "budget_spent": "Rs 0.6 crore",
                "budget_allocated": 9000000,
                "budget_spent_amount": 6000000,
                "hazard_type": "Pothole Cluster",
                "complaints": 38,
                "authority": "AP Roads & Buildings Dept",
                "last_repair": "2025-08-15",
                "next_review": "2026-06-25",
                "source_url": "https://data.gov.in/",
                "issue_summary": "Pothole cluster is slowing traffic and increasing two-wheeler risk.",
            },
            {
                "id": 6,
                "road": "NH-16 Vizag Bypass",
                "name": "NH-16 Vizag Bypass",
                "type": "NH",
                "district": "Visakhapatnam",
                "state": "Andhra Pradesh",
                "status": "Critical",
                "risk": "High",
                "severity": "high",
                "lat": 17.6868,
                "lng": 83.2185,
                "contractor": "PNC Infratech",
                "budget_sanctioned": "Rs 1.8 crore",
                "budget_spent": "Rs 1.4 crore",
                "budget_allocated": 18000000,
                "budget_spent_amount": 14000000,
                "hazard_type": "Erosion and Potholes",
                "complaints": 67,
                "authority": "NHAI",
                "last_repair": "2025-12-03",
                "next_review": "2026-06-28",
                "source_url": "https://morth.nic.in/",
                "issue_summary": "Road edge erosion and potholes are creating lane discipline hazards.",
            },
            {
                "id": 7,
                "road": "MH-SH-27 Pune-Nashik Highway",
                "name": "MH-SH-27 Pune-Nashik Highway",
                "type": "SH",
                "district": "Nashik",
                "state": "Maharashtra",
                "status": "Reported",
                "risk": "Medium",
                "severity": "medium",
                "lat": 20.0059,
                "lng": 73.7898,
                "contractor": "Dilip Buildcon",
                "budget_sanctioned": "Rs 1.1 crore",
                "budget_spent": "Rs 0.2 crore",
                "budget_allocated": 11000000,
                "budget_spent_amount": 2000000,
                "hazard_type": "Missing Guard Rails",
                "complaints": 22,
                "authority": "Maharashtra PWD",
                "last_repair": "2026-02-02",
                "next_review": "2026-07-08",
                "source_url": "https://data.gov.in/",
                "issue_summary": "Missing guard rails have been reported near a highway curve.",
            },
        ]
